require("zhansj.keymap")
require("zhansj.set")
require("zhansj.packer")
require("zhansj.plugin_config.telescope")
require("zhansj.plugin_config.colorscheme")
require("zhansj.plugin_config.lualine")
require("zhansj.plugin_config.treesitter")
require("zhansj.plugin_config.lsp_config")
require("zhansj.plugin_config.completions")
require("zhansj.plugin_config.nvim-tree")

